version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - apimachinery
  - automount
  - baizeai
  - clientcmd
  - containerlogs
  - coordinationv1client
  - corev1
  - CUDA
  - CUDNN
  - dcgm
  - dcgmi
  - exitcode
  - fullname
  - Infof
  - jellydator
  - klog
  - KUBECONFIG
  - Kubeflow
  - leaderelection
  - metav1
  - NCCL
  - nvidiadiag
  - podstatus
  - pytorchjobs
  - resourcelock
  - samber
  - serviceaccount
  - stretchr
  - tfjobs
  - ttlcache
  - Warningf
ignoreWords: []
import: []
