apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kcover.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "kcover.serviceAccountName" . }}
rules:
  # Cluster resources
  - apiGroups:
    - ""
    resources:
    - nodes
    verbs:
    - get
    - list
    - watch
    - update
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - '*'
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch

  # Core v1 Pods
  - apiGroups:
    - ""
    resources:
    - pods
    - pods/logs
    verbs:
    - '*'

  # Batch v1 Jobs
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch

  # Kubeflow.org
  - apiGroups:
      - kubeflow.org
    resources:
      - paddlejobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kubeflow.org
    resources:
      - mpijobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kubeflow.org
    resources:
      - mxjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kubeflow.org
    resources:
      - paddlejobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kubeflow.org
    resources:
      - pytorchjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kubeflow.org
    resources:
      - tfjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kubeflow.org
    resources:
      - xgboostjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - '*'
