apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kcover.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "kcover.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kcover.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kcover.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
