apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kcover.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kcover.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app: {{ include "kcover.fullname" . }}-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      {{- $podLabels := deepCopy (default dict .Values.controller.podLabels) }}
      {{- $_ := set $podLabels "app" (printf "%s-controller" (include "kcover.fullname" .)) }}
      {{- with .Values.controller.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- toYaml $podLabels | nindent 8 }}
    spec:
      {{- with .Values.controller.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kcover.controllerServiceAccountName" . }}
      securityContext:
        {{- toYaml .Values.controller.podSecurityContext | nindent 8 }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: controller
          image: {{ template "controller.image" . }}
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          {{- with .Values.controller.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.controller.args }}
          args:
            {{- toYaml . | nindent 12 }}
            - --leader-elect={{ $.Values.controller.leaderElection.enabled }}
          {{- end }}
          {{- if not .Values.controller.args }}
          args:
            - --leader-elect={{ .Values.controller.leaderElection.enabled }}
          {{- end }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}
