apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kcover.agentServiceAccountName" . }}
  labels:
    {{- include "kcover.labels" . | nindent 4 }}
  {{- with .Values.agent.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kcover.controllerServiceAccountName" . }}
  labels:
    {{- include "kcover.labels" . | nindent 4 }}
  {{- with .Values.controller.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
