apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "fast-recovery.fullname" . }}-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fast-recovery.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "fast-recovery.fullname" . }}-agent
  template:
    metadata:
      {{- with .Values.agent.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "fast-recovery.fullname" . }}-agent
    spec:
      {{- with .Values.agent.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fast-recovery.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.agent.podSecurityContext | nindent 8 }}
      containers:
        - name: agent
          securityContext:
            {{- toYaml .Values.agent.securityContext | nindent 12 }}
          image: "{{ .Values.agent.image.registry }}/{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          env:
            - name: FAST_RECOVERY_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            {{- toYaml .Values.agent.resources | nindent 12 }}
